import random
from tkinter import *

def run():
    root = Tk()
    root.geometry('650x650')
    root['bg'] = 'red'

    cd = 50

    def toWhite():
        root['bg'] = 'white'
        lin1.config(bg='white')
        lin2.config(bg='white')
        lin3.config(bg='white')
        lin4.config(bg='white')
        lin5.config(bg='white', text='       '+str(random.randint(111111111111111111111111111, 999999999999999999999999999))+'         ')
        lin6.config(bg='white')
        lin7.config(bg='white')
        lin8.config(bg='white')
        lin9.config(bg='white')
        lin10.config(bg='white')
        lin11.config(bg='white')
        lin12.config(bg='white')
        lin13.config(bg='white')
        lin14.config(bg='white')
        lin15.config(bg='white')
        lin16.config(bg='white')
        lin17.config(bg='white')
        lin18.config(bg='white')
        lin19.config(bg='white')
        lin20.config(bg='white')
        lin21.config(bg='white')
        lin22.config(bg='white')
        lin23.config(bg='white')
        lin24.config(bg='white')
        root.after(cd, toRed)
    def toRed():
        root['bg'] = 'red'
        lin1.config(bg='red')
        lin2.config(bg='red')
        lin3.config(bg='red')
        lin4.config(bg='red')
        lin5.config(bg='red', text='       '+str(random.randint(111111111111111111111111111, 999999999999999999999999999))+'         ')
        lin6.config(bg='red')
        lin7.config(bg='red')
        lin8.config(bg='red')
        lin9.config(bg='red')
        lin10.config(bg='red')
        lin11.config(bg='red')
        lin12.config(bg='red')
        lin13.config(bg='red')
        lin14.config(bg='red')
        lin15.config(bg='red')
        lin16.config(bg='red')
        lin17.config(bg='red')
        lin18.config(bg='red')
        lin19.config(bg='red')
        lin20.config(bg='red')
        lin21.config(bg='red')
        lin22.config(bg='red')
        lin23.config(bg='red')
        lin24.config(bg='red')
        root.after(cd, toWhite)

    def fullscreen():
        root.attributes('-fullscreen', True, '-topmost', True)
    def onPress(event):
        root.destroy()
    fullscreen()
    root.bind('<Return>', onPress)

    lin1 = Label(text='            uu$$$$$$$$$$$uu                ', font='Area 15', fg='white', bg='red')
    lin2 = Label(text='          uu$$$$$$$$$$$$$$$$$uu            ', font='Area 15', fg='white', bg='red')
    lin3 = Label(text='         u$$$$$$$$$$$$$$$$$$$$$u           ', font='Area 15', fg='white', bg='red')
    lin4 = Label(text='        u$$$$$$$$$$$$$$$$$$$$$$$u          ', font='Area 15', fg='white', bg='red')
    lin5 = Label(text='       '+str(random.randint(111111111111111111111111111, 999999999999999999999999999))+'         ', font='Area 15', fg='white', bg='red')
    lin6 = Label(text='       u$$$$$$*    *$$$*    *$$$$$$u       ', font='Area 15', fg='white', bg='red')
    lin7 = Label(text='       *$$$$*       u$u        $$$$*       ', font='Area 15', fg='white', bg='red')
    lin8 = Label(text='        $$$u        u$u        u$$$        ', font='Area 15', fg='white', bg='red')
    lin9 = Label(text='        $$$u       u$$$u       u$$$        ', font='Area 15', fg='white', bg='red')
    lin10 = Label(text='         *$$$$uu$$$   $$$uu$$$$*           ', font='Area 15', fg='white', bg='red')
    lin11 = Label(text='          *$$$$$$$*   *$$$$$$$*            ', font='Area 15', fg='white', bg='red')
    lin12 = Label(text='            u$$$$$$$u$$$$$$$u              ', font='Area 15', fg='white', bg='red')
    lin13 = Label(text='             u$*$*$*$*$*$*$u               ', font='Area 15', fg='white', bg='red')
    lin14 = Label(text='  uuu        $$u$ $ $ $ $u$$       uuu     ', font='Area 15', fg='white', bg='red')
    lin15 = Label(text='  u$$$$       $$$$$u$u$u$$$       u$$$$    ', font='Area 15', fg='white', bg='red')
    lin16 = Label(text='  $$$$$uu      *$$$$$$$$$*     uu$$$$$$    ', font='Area 15', fg='white', bg='red')
    lin17 = Label(text='u$$$$$$$$$$$uu Press ENTER uuu$$$$$$$$$    ', font='Area 15', fg='white', bg='red')
    lin18 = Label(text='$$$$***$$$$$$$$$$uuu   uu$$$$$$$$$***$$$*  ', font='Area 15', fg='white', bg='red')
    lin19 = Label(text=' ***      **$$$$$$$$$$$uu **$***           ', font='Area 15', fg='white', bg='red')
    lin20 = Label(text='          uuuu **$$$$$$$$$$uuu             ', font='Area 15', fg='white', bg='red')
    lin21 = Label(text=' u$$$uuu$$$$$$$$$uu **$$$$$$$$$$$uuu$$$    ', font='Area 15', fg='white', bg='red')
    lin22 = Label(text=' $$$$$$$$$$****           **$$$$$$$$$$$*   ', font='Area 15', fg='white', bg='red')
    lin23 = Label(text='   *$$$$$*                      **$$$$**   ', font='Area 15', fg='white', bg='red')
    lin24 = Label(text='     $$$*                         $$$$*    ', font='Area 15', fg='white', bg='red')
    lin1.pack()
    lin2.pack()
    lin3.pack()
    lin4.pack()
    lin5.pack()
    lin6.pack()
    lin7.pack()
    lin8.pack()
    lin9.pack()
    lin10.pack()
    lin11.pack()
    lin12.pack()
    lin13.pack()
    lin14.pack()
    lin15.pack()
    lin16.pack()
    lin17.pack()
    lin18.pack()
    lin19.pack()
    lin20.pack()
    lin21.pack()
    lin22.pack()
    lin23.pack()
    lin24.pack()

    toWhite()

    root.mainloop()